version: '3.0'

services:
  app:
    build: 
      context: .
      dockerfile: ./Dockerfile.production
    image: segrishanin/devops-for-programmers-project-74:latest
    command: bash -c 'sleep 10 && npm run test'
    depends_on:
      - db
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    env_file:
      - .env
    networks:
      - dev-nw

  db:
    image: postgres:15.3
    restart: always
    environment:
        POSTGRES_DB: ${DATABASE_NAME}
        POSTGRES_USER: ${DATABASE_USERNAME}
        POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    networks:
      - dev-nw

networks:
  dev-nw:
    driver: bridge

      