services:
  app:
    command: npm run dev
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
  caddy:
    image: caddy:2.6.4-alpine
    restart: unless-stopped
    volumes:
      - ${PWD}/services/caddy/Caddyfile:/etc/caddy/Caddyfile
    ports:
      - "80:80"
      - "443:443"
