version: '3.0'

services:
  app:
    build: 
      context: .
      dockerfile: ./Dockerfile.production
    image: segrishanin/devops-for-programmers-project-74:latest
    command: npm test
    depends_on:
      - db

  db:
    image: postgres:15.3
    restart: always
    environment:
        POSTGRES_DB: fastify
        POSTGRES_USER: user
        POSTGRES_PASSWORD: password

      