name: docker-push

on:
    push:
        branches:
            - main

env:
    DOCKER_IMAGE: "segrishanin/devops-for-programmers-project-74"
    DOCKER_TAG: "latest"

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - 
                name: Git checkout
                uses: actions/checkout@v3
            -
                name: Make env file
                run: |
                    touch .env
                    echo DATABASE_HOST = db >> .env
                    echo DATABASE_PORT = 5432 >> .env
                    echo DATABASE_NAME = fastify >> .env
                    echo DATABASE_USERNAME = user >> .env
                    echo DATABASE_PASSWORD = password >> .env
                    cat .env
            -
                name: Run Compose with tests
                uses: isbang/compose-action@v1.4.1
                with:
                    compose-file: "./docker-compose.yml"
                    up-flags: "--abort-on-container-exit"
                    services: app

    docker:
        runs-on: ubuntu-latest
        needs:
            - test
        steps:
            -
                name: Set up QEMU
                uses: docker/setup-qemu-action@v2
            -
                name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v2
            -
                name: Login to Docker Hub
                uses: docker/login-action@v2
                with:
                    username: ${{ secrets.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_TOKEN }}
            -
                name: Build and push
                uses: docker/build-push-action@v4
                with:
                    push: true
                    tags: ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}
